### PR TITLE
Multiversion support from 1.9 onwards without NMS

### PR DESCRIPTION
**Pull request by yannicklamprecht**
### What is the purpose of this pull request?
Making a break and adding support for versions from 1.9 onwards.

### How do your changes address the purpose?
Dropping all NMS classes and using the api that is preset from 1.9 onwards. Probably even earlier.

### CODE REVIEW

**Comment by mastercake10** [comment]
So this drops action bar support for bukkit < 1.12? Can you add back the other nms modules and use the spigot method for all other versions?

Also we don't increment the major version when there weren't huge changes.

**Comment by yannicklamprecht** [comment]
> So this drops action bar support for bukkit < 1.12? Can you add back the other nms modules and use the spigot method for all other versions?
> 
> Also we don't increment the major version when there weren't huge changes.

I'll see how far back the API is going and hopefully don't even need to do that.

**Comment by yannicklamprecht** [comment]
Perfect except 1.8.x  all Spigot versions have that API. So it can be fully ignored.

**Comment by mastercake10** [comment]
Why can it fully be ignored? 5.5 percent of all servers that use TimeIsMoney are still using 1.8.8, I don't really want to drop support for that version..

**Pull request merged**
